recipe: default.v1
assistant_id: tfg
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LanguageModelFeaturizer"
    model_name: "gpt"
  - name: "DIETClassifier"
    epochs: 100
    entity_recognition: False
    constrain_similarities: True
    use_masked_language_model: True
    evaluate_on_number_of_examples: 520
    evaluate_every_number_of_epochs: 1
    checkpoint_model: True
    tensorboard_log_directory: './GPT_EXP2'
    tensorboard_log_level: 'epoch'
    