recipe: default.v1
assistant_id: tfg
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LanguageModelFeaturizer"
    model_name: "camembert"
  - name: "DIETClassifier"
    epochs: 100
    entity_recognition: False
    constrain_similarities: True
    evaluate_on_number_of_examples: 520
    evaluate_every_number_of_epochs: 1
    checkpoint_model: True
