recipe: default.v1
assistant_id: tfg
language: en
pipeline:
  - name: "SpacyNLP"
    model: "en_core_web_md"
  - name: "SpacyTokenizer"
  - name: "SpacyFeaturizer"
  - name: 'LexicalSyntacticFeaturizer'
  - name: "DIETClassifier"
    epochs: 100
    entity_recognition: False
    constrain_similarities: True
    embedding_dimension: 30
    evaluate_on_number_of_examples: 520
    evaluate_every_number_of_epochs: 1
    checkpoint_model: True
    tensorboard_log_directory: './spacy2_EXP3'
    tensorboard_log_level: 'epoch'
