recipe: default.v1
assistant_id: tfg
language: en
pipeline:
  - name: "WhitespaceTokenizer"
  - name: "LanguageModelFeaturizer"
    model_name: "bert"
    model_weights: "rasa/LaBSE"
  - name: "DIETClassifier"
    epochs: 100
    constrain_similarities: True
    entity_recognition: False
    number_of_transformer_layers: 3
    evaluate_on_number_of_examples: 520
    evaluate_every_number_of_epochs: 1
    checkpoint_model: True
    tensorboard_log_directory: './bert4'
    tensorboard_log_level: 'epoch'
    
